Week 2 Assignments
pesto-students/p5-subhadip-anugrahpaul2000 pull request #5
Opened 2022-08-27 05:10 UTC by anugrahpaul2000

Assignment 1 & 2 Finished

2022-08-30 15:03 UTC, subhadip-pesto requested changes

2022-08-30 15:03 UTC, subhadip-pesto commented on Week-2/Assignment-1/index.html
> +      <div class="footer">
don't put this form inside footer, and use footer tag

2022-08-30 15:03 UTC, subhadip-pesto commented on Week-2/Assignment-1/index.html
> +                onclick="this.setAttribute('value', this.value);"
why you have added this onClick event?

2022-08-30 15:03 UTC, subhadip-pesto commented on Week-2/Assignment-1/style.css
> +  justify-content: center;
Floating Labels Should be left aligned, Keeping labels in the center is not a good UX.

2022-08-30 15:03 UTC, subhadip-pesto commented on Week-2/Assignment-2/style.css
> +  rotate: 90deg;
put this rotate, in transformTopLeft, and for the rest do the same.

2022-08-30 17:40 UTC, anugrahpaul2000 commented on Week-2/Assignment-1/index.html
> +      <div class="footer">
Done Sir

2022-08-30 17:41 UTC, anugrahpaul2000 commented on Week-2/Assignment-1/index.html
> +                onclick="this.setAttribute('value', this.value);"
Was using on click event to modify Select tag & make it look beautiful but removed that feature and forgot to remove the event.

2022-08-30 17:42 UTC, anugrahpaul2000 commented on Week-2/Assignment-1/style.css
> +  justify-content: center;
Ok sir. but this a sub div within a div. Align Left and center isn't actually doing anything.

2022-08-30 17:44 UTC, anugrahpaul2000 commented on Week-2/Assignment-2/style.css
> +  rotate: 90deg;
Tried Sir but animation breaks.

2022-08-30 17:46 UTC, anugrahpaul2000 commented
@subhadip-pesto Sir Please Review Once again.

2022-08-31 17:42 UTC, anugrahpaul2000 commented
@subhadip-pesto Updated as per 1-on-1 session Discussion

2022-09-01 03:17 UTC, subhadip-pesto approved these changes

2022-09-01 14:26 UTC, merged