Week 3 Assignments
pesto-students/p5-subhadip-anugrahpaul2000 pull request #6
Opened 2022-09-01 18:29 UTC by anugrahpaul2000

Assignments Finished

2022-09-01 18:38 UTC, subhadip-pesto requested changes

2022-09-01 18:38 UTC, subhadip-pesto commented on .vscode/launch.json
> +{
Don't commit this file

2022-09-01 18:38 UTC, subhadip-pesto commented on Week-3/Assignment-4/index.js
> +        status() {
a proper name would be "listItems" instead of "status"

2022-09-02 19:08 UTC, anugrahpaul2000 commented
@subhadip-pesto Kindly review once Again.

2022-09-03 04:20 UTC, subhadip-pesto approved these changes

2022-09-03 06:02 UTC, merged