Week 4 Assignments
pesto-students/p5-subhadip-anugrahpaul2000 pull request #7
Opened 2022-09-10 18:19 UTC by anugrahpaul2000

Assignments Done

2022-09-12 08:50 UTC, subhadip-pesto requested changes

2022-09-12 08:50 UTC, subhadip-pesto commented on Week-4/Assignment-1/index.js
> +  return new Promise((resolve, reject) => {
Create your custom promise polyfill

2022-09-12 08:50 UTC, subhadip-pesto commented on Week-4/Assignment-2/index.js
> +class Person
in javascript use braces like this

class Person {

}

The reason is most of the developers use this way of putting the braces, even later when you will be introduced to the linters, that will also follow the same.

2022-09-13 17:45 UTC, anugrahpaul2000 commented
@subhadip-pesto Updated Assignments

2022-09-14 16:52 UTC, anugrahpaul2000 commented
Updated Assignment @subhadip-pesto

2022-09-17 09:32 UTC, subhadip-pesto approved these changes

2022-09-17 12:20 UTC, merged