Week 5 Assignments Done
pesto-students/p5-subhadip-anugrahpaul2000 pull request #8
Opened 2022-09-17 18:06 UTC by anugrahpaul2000

@subhadip-pesto Kindly find the Assignment.

2022-09-19 20:08 UTC, subhadip-pesto requested changes
Do not commit .node_modules folder, use a .gitignore file and add node_modules as an entry over there.

2022-09-19 20:08 UTC, subhadip-pesto commented on Week-5/Assignment-1/index.js
> +    .then((res) => {
in case of async await why are you using then()? await getUser(uId) should return the resolved value

2022-09-19 20:08 UTC, subhadip-pesto commented on Week-5/Assignment-4/math.test.js
> +test(`Add ${val1} + ${val2} to equal ${val1 + val2}`, () => {
use describe and it

2022-09-24 06:03 UTC, anugrahpaul2000 commented
@subhadip-pesto Fixed The Assignments

2022-10-01 03:59 UTC, subhadip-pesto approved these changes

2022-10-01 04:02 UTC, merged