Week 6 | Assignment 3 & 4
pesto-students/p5-subhadip-anugrahpaul2000 pull request #9
Opened 2022-09-20 15:09 UTC by anugrahpaul2000

2022-09-24 04:23 UTC, subhadip-pesto requested changes

2022-09-24 04:23 UTC, subhadip-pesto commented on Week-6/Assignment-3/index.js
> +  for (const el of Object.keys(count)) {
here the complexity is becoming O(n)^2

2022-09-24 04:23 UTC, subhadip-pesto commented on Week-6/Assignment-3/index.js
> +  const count = {
what if its not given that array will only contains 0,1,2 s? avoid hard coding.

2022-09-24 04:23 UTC, subhadip-pesto commented on Week-6/Assignment-4/index.js
> +  for (let i = 0; i < prices.length; i++) {
can be done in O(n)

2022-09-25 11:57 UTC, anugrahpaul2000 commented
@subhadip-pesto Please Review the Assignments when you find time.

2022-11-09 06:16 UTC, subhadip-pesto approved these changes

2022-11-09 15:54 UTC, merged